<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script language="javascript" src="ajax.js" ></script>
        <style type="text/css">
            #loadding {color:red; font-size: 20px; font-weight: bold; text-align: center;
position: fixed;
bottom:150px;
left:115px;
z-index:100;
}
            .item {height: 50px; border: solid 2px blue; background: #CCCCCC; 
                  line-height: 50px; color: blue; text-align: center; font-weight: bold; margin: 20px 0px;}
            .hidden {display: none}
          

@keyframes ldio-vl1jgr766el-o {
    0%    { opacity: 1; transform: translate(0 0) }
   49.99% { opacity: 1; transform: translate(80px,0) }
   50%    { opacity: 0; transform: translate(80px,0) }
  100%    { opacity: 0; transform: translate(0,0) }
}
@keyframes ldio-vl1jgr766el {
    0% { transform: translate(0,0) }
   50% { transform: translate(80px,0) }
  100% { transform: translate(0,0) }
}
.ldio-vl1jgr766el div {
  position: absolute;
  width: 20px;
  height: 20px;
  border-radius: 50%;
  top: 60px;
  left: 20px;
}
.ldio-vl1jgr766el div:nth-child(1) {
  background: #e90c59;
  animation: ldio-vl1jgr766el 1s linear infinite;
  animation-delay: -0.5s;
}
.ldio-vl1jgr766el div:nth-child(2) {
  background: #46dff0;
  animation: ldio-vl1jgr766el 1s linear infinite;
  animation-delay: 0s;
}
.ldio-vl1jgr766el div:nth-child(3) {
  background: #e90c59;
  animation: ldio-vl1jgr766el-o 1s linear infinite;
  animation-delay: -0.5s;
}
.loadingio-spinner-dual-ball-qzxe5sacyb8 {
  width: 100%;
  height: 100%;
  display: inline-block;
  overflow: hidden;
  background-color: rgba(0, 0, 0, 0);
}
.ldio-vl1jgr766el {
  width: 200px;
  height: 100px;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-vl1jgr766el div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>
        
    </head>
    <body>
     
    
        <div id="content" class="row">
         
  <?php  include 'data.php'; ?>


</div>
            
       
<div id="loadding" class="hidden text-center text-info">
  <div class="spinner-border" role="status">
    <div class="loadingio-spinner-dual-ball-qzxe5sacyb8"><div class="ldio-vl1jgr766el">
<div></div><div></div><div></div>
</div></div>
  </div>
</div>
        
    </body>
</html>